variable "vcd_url" {
  description = "API endpoint URL"
  type        = string
  default     = "https://ucp.uniserver.nl/api"
}

variable "vcd_user" {
  description = "user account for vCloud Director"
  type        = string
}

variable "vcd_password" {
  description = "password for vCloud Director"
  type        = string
}

variable "vcd_auth_type" {
  description = "authentication method"
  type        = string
}

variable "vcd_api_token" {
  description = "API token generated by user"
  type        = string
}

variable "org_name" {
  description = "organization"
  type        = string
}

variable "org_vdc" {
  description = "organization virtual datacenter"
  type        = string
}

variable "vcd_edgegateway" {
  description = "already provisioned edge gateway to be used"
  type        = string
}

variable "vcd_allow_unverified_ssl" {
  description = "disable check on SSL certificate"
  type        = bool
  default     = false
}

variable "webdmz_cidr" {
  description = "subnet address to use as DMZ network, in CIDR notation"
  type        = string
}

variable "webdmz_gateway" {
  description = "gateway address to use in DMZ network"
  type        = string
}

variable "webdmz_staticippool_start" {
  description = "static IP pool first IP"
  type        = string
}

variable "webdmz_staticippool_end" {
  description = "static IP pool last IP"
  type        = string
}

variable "dns1" {
  type = string
}

variable "dns2" {
  type = string
}

variable "ova_image" {
  description = "OVA to use"
  type        = string
}

